# Generated by Django 5.1.1 on 2024-09-07 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HyperlinkedModelSerializerApp', '0003_diploma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='HyperlinkedModelSerializerApp.student'),
        ),
    ]
